spring.application.name=login-backend
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=SYSTEM
spring.datasource.password=Myoracledb@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080